-- MySQL Script generated by MySQL Workbench
-- Fri Jun  4 10:03:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajos` (
  `idTrabajo` INT NOT NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `Salario` INT NOT NULL,
  PRIMARY KEY (`idTrabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personas` (
  `idPersonas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Sexo` VARCHAR(6) NOT NULL,
  `idTrabajo` INT NOT NULL,
  PRIMARY KEY (`idPersonas`),
  UNIQUE INDEX `idAmigos_UNIQUE` (`idPersonas` ASC) VISIBLE,
  INDEX `idTrabajo_idx` (`idTrabajo` ASC) VISIBLE,
  CONSTRAINT `idTrabajo`
    FOREIGN KEY (`idTrabajo`)
    REFERENCES `mydb`.`Trabajos` (`idTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Trabajos`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (1, 'Profesor', 'Sevilla', 'España', 24000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (2, 'Profesor', 'Barcelona', 'España', 28000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (3, 'Médico', 'Madrid', 'España', 30000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (4, 'Médico', 'Valencia', 'España', 29000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (5, 'Enfermero', 'Lisboa', 'Portugal', 24000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (6, 'Enfermero', 'Madrid', 'España', 25000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (7, 'Bombero', 'Barcelona', 'España', 20000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (8, 'Bombero', 'Madrid', 'Escaña', 24000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (9, 'Profesor', 'Paris', 'Francia', 34000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (10, 'Profesor', 'Lisboa', 'Portugal', 27000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (11, 'Profesor', 'Madrid', 'España', 28500);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (12, 'Médico', 'Paris', 'Francia', 39000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (13, 'Médico', 'Lisboa', 'Portugal', 35000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (14, 'Médico', 'Barcelona', 'España', 32000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (15, 'Enfermero', 'Barcelona', 'España', 28000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (16, 'Enfermero', 'Sevilla', 'España', 22000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (17, 'Enfermero', 'Paris', 'Francia', 30000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (18, 'Bombero', 'Sevilla', 'España', 22000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (19, 'Bombero', 'Lisboa', 'Portugal', 26000);
INSERT INTO `mydb`.`Trabajos` (`idTrabajo`, `Puesto`, `Ciudad`, `Pais`, `Salario`) VALUES (20, 'Bombero', 'Paris', 'Francia', 30000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Personas`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (1, 'Antonio', 'Pérez', 30, 'Hombre', 1);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (2, 'Luisa', 'Cortes', 42, 'Mujer', 3);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (3, 'Ana', 'Fernández', 26, 'Mujer', 12);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (4, 'Eduardo', 'De la Casa', 23, 'Hombre', 14);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (5, 'Fernando', 'Martínez', 28, 'Hombre', 12);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (6, 'Francisco', 'Mandattori', 35, 'Hombre', 16);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (7, 'José', 'Fernández', 38, 'Hombre', 2);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (8, 'Adolfo', 'Jiménez', 46, 'Hombre', 1);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (9, 'Josep', 'Puig', 41, 'Hombre', 2);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (10, 'Marcos', 'Cuadros', 24, 'Hombre', 3);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (11, 'María', 'Del Señor', 37, 'Mujer', 5);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (12, 'Eloisa', 'Campanilla', 18, 'Mujer', 6);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (13, 'Clara', 'Campoamor', 50, 'Mujer', 7);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (14, 'Esther', 'Cuenca', 33, 'Mujer', 11);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (15, 'Adela', 'Mar', 36, 'Mujer', 10);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (16, 'Javier', 'Pino', 34, 'Hombre', 20);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (17, 'Antonio', 'Van der Vaar', 47, 'Hombre', 4);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (18, 'Fernando', 'Viejo', 18, 'Hombre', 6);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (19, 'Luis', 'Nuñez', 55, 'Hombre', 7);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (20, 'Felipe', 'González', 68, 'Hombre', 8);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (21, 'Aurelio', 'Buendía', 70, 'Hombre', 9);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (22, 'Jorge', 'Borgoña', 44, 'Hombre', 13);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (23, 'Ana', 'Cuesta', 26, 'Mujer', 14);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (24, 'Emma', 'Watson', 30, 'Mujer', 15);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (25, 'María', 'Abad', 34, 'Mujer', 17);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (26, 'Hugo', 'Boss', 38, 'Hombre', 18);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (27, 'Adela', 'Galletas', 32, 'Mujer', 19);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (28, 'Antonio', 'Casamayor', 34, 'Hombre', 20);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (29, 'Francisco', 'Del Campo', 35, 'Hombre', 17);
INSERT INTO `mydb`.`Personas` (`idPersonas`, `Nombre`, `Apellido`, `Edad`, `Sexo`, `idTrabajo`) VALUES (30, 'Luisa', 'Pino', 29, 'Mujer', 9);

COMMIT;

